log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

db:
  url: "postgres://relayer:relayer@localhost:5432/relayer?sslmode=disable"

core:
  addr: https://rpc.node1.mainnet-beta.rarimo.com:443

cosmos:
  addr: core-api.node1.mainnet-beta.rarimo.com:443
  enable_tls: true


evm:
  chains:
    - name: "Swisstronik"
      contract_address: "0xC82C9ac7B1A1c58957e39987Ad37332C3b9C1299"
      submitter_private_key: ""
      rpc: https://json-rpc.testnet.swisstronik.com
      chain_id: 1291

relay:
  catchup_disabled: false
  issuer_id: [ '', '' ]
  disable_filtration: true