name: Build Rarimo Identity Relayer service docker image
on:
  push:
    branches:
      - 'main'
      - 'master'

permissions:
  packages: write

jobs:
  docker-main:
    name: docker-main
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/sigmagmbh/rarimo-polygonid-identity-relayer-svc:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max